// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "小蔡資訊",
            "url": "https://jo87jimmy.github.io/",
            "email": "jo87jimmy@gmail.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/ai/image/orc/text": {
            "post": {
                "description": "圖片Servi轉文字",
                "consumes": [
                    "json multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "ai 圖片轉文字"
                ],
                "summary": "AI 圖片Servi轉文字",
                "parameters": [
                    {
                        "type": "file",
                        "description": "要上傳的圖片",
                        "name": "file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "成功時回傳過濾後的 rec_texts 陣列",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "無法取得圖片",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "內部錯誤，例如圖片儲存錯誤、執行 CLI 錯誤或無法讀取結果檔案",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:9536",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OCRGO API",
	Description:      "OCR API",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
